---
- name: ensure unzip package is available
  package:
    name: unzip
    state: present

- name: create promtail group
  group:
    name: "{{ promtail_system_group }}"
    state: present
    system: true
  when: promtail_system_group != "root"

- name: create the promtail user
  user:
    name: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"
    groups: "{{ promtail_user_additional_groups }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: promtail_system_user != "root"

- name: ensure /usr/local/bin exists
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: create config dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ promtail_system_group }}"
    mode: 0770
  with_items:
    - "{{ promtail_config_dir }}"

- name: create application dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ promtail_system_user }}"
    group: "{{ promtail_system_group }}"
    mode: 0755
  with_items:
    - "{{ promtail_install_dir }}"
    - "{{ promtail_install_dir }}/{{ promtail_version }}"

- name: check promtail binary
  stat:
    path: "{{ promtail_install_dir }}/{{ promtail_version }}/promtail-linux-amd64"
  register: promtail_binary

- name: download promtail binaries
  get_url:
    url: "{{ promtail_dist_url }}"
    dest: "{{ promtail_tmp_dir }}/{{ promtail_version }}_promtail-linux-amd64.zip"
    force: true
    checksum: "sha256:{{ __promtail_checksum }}"
  when: not promtail_binary.stat.exists

- name: unpack promtail binaries
  ignore_errors: "{{ ansible_check_mode }}"
  unarchive:
    src: "{{ promtail_tmp_dir }}/{{ promtail_version }}_promtail-linux-amd64.zip"
    dest: "{{ promtail_install_dir }}/{{ promtail_version }}"
    creates: "{{ promtail_install_dir }}/{{ promtail_version }}/promtail-linux-amd64"
    remote_src: true

- name: create symlink to latest version
  notify:
    - restart promtail
  ignore_errors: "{{ ansible_check_mode }}"
  file:
    state: link
    src: "{{ promtail_install_dir }}/{{ promtail_version }}/promtail-linux-amd64"
    dest: /usr/local/bin/promtail
    mode: 0755

- name: write config
  notify:
    - restart promtail
  template:
    src: config.j2
    dest: "{{ promtail_config_file }}"
    owner: root
    group: "{{ promtail_system_group }}"

- name: create systemd service unit
  notify:
    - restart promtail
  template:
    src: service.j2
    dest: /etc/systemd/system/promtail.service
