name: Static code analysis
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ansible-later:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ansible-later
      uses: patrickjahns/ansible-later-action@master
      with:
        config: ".later.yml"
        path: "**/*.yml"
